### PR TITLE
Add support for LaTeX

### PR DESCRIPTION
**Pull request by yagarea**
I added LaTeX support using jektex plugin.

### CODE REVIEW

**Comment by gernotstarke** [comment]
@yagarea I don't understand the ramifications of this PR: What exactly does the site gain with this plugin? 

imho we currently don't require mathematical formulas, nor does it contain TeX expressions...

Would be great if you could explain a bit...

**Comment by yagarea** [comment]
this plugin is server side so it will not bloat much the site it self.
I think it is a good feature. Specially when used as template.

I did this PR for hacktoberfest. I hope you find it useful/

**Comment by gernotstarke** [comment]
Sorry Jan, I won't merge features with use-cases I don't understand: Please explain in a bit more detail what one would gain?
In what cases would LaTeX add value to this site?

**Comment by gernotstarke** [comment]
It does not help or advance this repo in any way. I suspect it was used to get Hacktoberfest credentials, therefore I close it.

**Pull request closed without merging**
